version: "3.1"

services:
    ersatztv:
        build:
            context: .
        ports:
            - "8989:80"
        volumes:
            - ersatztv:/root/.local/share/ersatztv
            #- /media/shared:/media/shared:ro 
volumes:
    ersatztv:
